export const GET_POKEMONS = 'GET_POKEMONS'
export const GET_POKE_DETAIL = 'GET_POKE_DETAIL'
export const GET_BY_POKENAME = 'GET_BY_POKENAME'
export const POST_NEW_POKE  = 'POST_NEW_POKE '
export const GET_POKE_TYPES = 'GET_POKE_TYPES'
export const FILTER_CREATE_POKE = 'FILTER_CREATE_POKE'
export const ORDER_BY_NAME = 'ORDER_BY_NAME'
export const ORDER_BY_ATTACK = 'ORDER_BY_ATTACK'
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE'
export const CLEAR_DETAIL = 'CLEAR_DETAIL'
export const CLEAR_HOME = 'CLEAR_HOME'
export const EMPTY = 'EMPTY'


