const GET_POKEMONS = 'GET_POKEMONS'
const GET_POKE_DETAIL = 'GET_POKE_DETAIL'
const GET_BY_POKENAME = 'GET_BY_POKENAME'
const POST_NEW_POKE  = 'POST_NEW_POKE '
const GET_POKE_TYPES = 'GET_POKE_TYPES'
const FILTER_CREATE_POKE = 'FILTER_CREATE_POKE'
const ORDER_BY_NAME = 'ORDER_BY_NAME'
const ORDER_BY_ATTACK = 'ORDER_BY_ATTACK'
const FILTER_BY_TYPE = 'FILTER_BY_TYPE'
const CLEAR_DETAIL = 'CLEAR_DETAIL'
const CLEAR_HOME = 'CLEAR_HOME'
const EMPTY = 'EMPTY'


export default { 
    GET_POKEMONS,
    GET_POKE_DETAIL,
    GET_BY_POKENAME,
    POST_NEW_POKE ,
    GET_POKE_TYPES,
    FILTER_CREATE_POKE,
    ORDER_BY_NAME,
    ORDER_BY_ATTACK,
    FILTER_BY_TYPE,
    CLEAR_HOME,
    CLEAR_DETAIL,
    EMPTY,
}